"""
Django settings for sgmsc project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import urlparse


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'usuarios',
    'salas',
    'horarios',
    'semestres',
    'asignaciones',
    'cambios',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
]

AUTH_USER_MODEL = 'usuarios.Usuario'
LOGIN_URL = 'login'
PASSWORD_RESET_TIMEOUT = 3600 # 1 hora en segundos para el token de restablecimiento de contraseña

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sgmsc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sgmsc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'), 
    }
}

# 1. Definir la ruta base (esto ya debería estar en tu archivo)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Cargar el archivo .env especificando la ruta exacta
# Esto asegura que Django lo encuentre sin importar desde dónde corras el servidor
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Para desarrollo (los correos salen en la terminal):
# Email (Gmail SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_JEFE_DEPARTAMENTO = os.getenv("EMAIL_JEFE_DEPARTAMENTO")

#ESTA LÍNEA (Le dice a Django cuál es el remitente por defecto)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Dominio seguro para enlaces en correos (mitiga Host Header Injection).
# SITE_URL es la única fuente de verdad; SITE_PROTOCOL/SITE_DOMAIN se derivan.
_raw_site_url = os.getenv("SITE_URL", "http://localhost:8000").strip().rstrip("/")
_parsed_site_url = urlparse(
    _raw_site_url if "://" in _raw_site_url else f"http://{_raw_site_url}"
)
if _parsed_site_url.scheme and _parsed_site_url.hostname:
    SITE_PROTOCOL = _parsed_site_url.scheme
    SITE_DOMAIN = _parsed_site_url.netloc
    SITE_URL = f"{SITE_PROTOCOL}://{SITE_DOMAIN}"
else:
    SITE_PROTOCOL = "http"
    SITE_DOMAIN = "localhost:8000"
    SITE_URL = f"{SITE_PROTOCOL}://{SITE_DOMAIN}"


# --- TEMPORALMENTE PARA PROBAR ---
print(f"DEBUG: El correo cargado es: {EMAIL_HOST_USER}")
if EMAIL_HOST_USER is None:
    print("ERROR: No se encontró el archivo .env o las variables están vacías.")
# --------------------------------------------

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
