# Generated by Django 6.0.4 on 2026-05-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
    ]
