# Generated by Django 6.0.4 on 2026-06-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semestres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], verbose_name='Periodo'),
        ),
    ]
