# Generated by Django 6.0.4 on 2026-06-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_alter_asignacion_semestre_delete_semestre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'verbose_name': 'Asignación', 'verbose_name_plural': 'Asignaciones'},
        ),
    ]
